var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dev/components/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0cy5-xh._.js")
R.c("server/chunks/ssr/_0nxm3nr._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__07-h6_m._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0pfvm3n._.js")
R.c("server/chunks/ssr/_0h8jilc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_dev_components_page_actions_0i-3k4-.js")
R.m(32983)
module.exports=R.m(32983).exports
